### ISSUE TITLE
[Error] Tactical Grid disappears while dragging tokens with the mouse.

### ISSUE THREAD

**Issue by PlasticMohawk** [Aedif/tactical-grid#2]
Tactical Grid v. 1.5.0

On hover over a token, the grid is visible.
Clicking (and holding) a token, the grid is visible.
Dragging the token, the grid is invisible.
Releasing the token, the grid is visible again.

Additionally, during the interaction, my console log is spammed with errors like these:

TypeError: Error thrown in hooked function '' for hook 'hoverToken'. Cannot read properties of undefined (reading 'hasOwnProperty')
[Detected 2 packages: aedifs-tactical-grid, system:pf2e]
    at GridMaskContainer.updateGridMask (container.js:99:69)
    at GridMaskContainer.drawMask (container.js:62:14)
    at Object.fn (tactical-grid.js:65:27)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at TokenPF2e._onHoverIn (foundry.js:25515:11)
    at TokenPF2e._onHoverIn (foundry.js:47345:18)
    at TokenPF2e._onHoverIn (main.bundle.js:1:601832)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleMouseOver (foundry.js:27930:17)
    at a.emit (index.js:181:35)
    at TokenPF2e.emitHoverIn (main.bundle.js:1:598506)
    at TokenPF2e._onDragLeftDrop (main.bundle.js:1:601745)

**Comment by Aedif** [comment]
Couldn't reproduce the invisible grid on drag, but the error should be resolved now. See if release `1.5.1` resolves the issue for you.
